# Generated by Django 4.0.6 on 2022-08-23 12:51

import Feeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=Feeds.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
