# Generated by Django 4.0.6 on 2022-08-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0002_alter_posts_caption_alter_posts_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
