# Generated by Django 4.0.6 on 2022-09-01 12:50

import Feeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0003_remove_posts_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, default=False, max_length=1500, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pictures',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=Feeds.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
